use_frameworks!
target 'SolanaSwift_Tests' do
  pod 'SolanaSwift', :path => '../'
  pod 'RxBlocking'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
