#!/bin/bash

# exit when any command fails
set -e

# set version in README.md
gsed -i 's/pod '\'SolanaSwift\'', '\''~> '.*''\''/pod '\'SolanaSwift\'', '\''~> '$1'\'\''/g' README.md

# set version in podspec
gsed -i 's/s.version.*= '.*'/s.version          = '\'''$1'\'\''/g' SolanaSwift.podspec

# lint podspec
pod lib lint SolanaSwift.podspec --allow-warnings

# commit and tag
git add 'SolanaSwift.podspec' 'README.md'
git commit -m "feat: upversion to '$1'"
git tag ''$1''
git push origin --tags

# upload in cocoapods
pod trunk push SolanaSwift.podspec --allow-warnings
